### ISSUE TITLE
Support for api/v2/apps/ to access app specific data

### ISSUE THREAD

**Issue by shokeenAnil** [cloudbees-oss/zendesk-java-client#172]
Is there any way to access apps information via client ? Currently, there is no method in client that supports requests like `https://yoursubdomain.zendesk.com/api/v2/apps/12345/public_key.pem`. 

Any workaround for this via zendesk client?

**Comment by matthewtckr** [comment]
Zendesk API Reference: https://developer.zendesk.com/rest_api/docs/core/apps

Hi @shokeenAnil, it looks like those methods would need to be added to the project, otherwise you could implement your own HTTP calls to the Zendesk APIs.

If you're willing and able to contribute these new methods to the project, I'd recommend reading the [Contributing Guide](https://github.com/cloudbees/zendesk-java-client/blob/master/CONTRIBUTING.adoc).

Regards,
