### ISSUE TITLE
Breaking change from Zendesk means searches fail if more than 10 pages long

### ISSUE THREAD

**Issue by emercer** [cloudbees-oss/zendesk-java-client#295]
**Describe the bug**
https://develop.zendesk.com/hc/en-us/articles/360022563994--BREAKING-New-Search-API-Result-Limits

In a nutshell, if your search is more than 1,000 results long, Zendesk will still link to the 11th page of results (100 per page) but if you request it, it will fail with HTTP 422.

**To Reproduce**
Make any broad enough search.

**Expected behavior**
Since Zendesk refuses to return any result past 1,000 - but still offers pages past page 10 to the pagination engine - the pagination handler (`Zendesk.handleList()`) needs to stop at page 10 always.

**Comment by s0fs** [comment]
Also. I try to find  this method in client - GET /api/v2/search/count.json?query={search_string}
That will  help when i get response HTTP 422 . 

Are there similar methods here?

https://developer.zendesk.com/rest_api/docs/support/search#show-results-count

**Comment by aheritier** [comment]
@emercer it makes sense to change the behavior. We have to take care to not break something else like incremental export apis.
@s0fs no, the count method isn't implemented AFAICS

**Comment by srilavanyapaleti** [comment]
Have few questions related to this issue/expected behaviour mentioned in the first comment.

1.  In the case where the search results are more than 1000, how could we fetch the remaining results if the `handleList` stops at page 10?
The Zendesk Search API response returns the next page and total count of results. My initial thoughts of handling this breaking change was to write some custom code based on the count parameter and using url in next page to get the remaining results. However, the API client methods returns the list of tickets parsing the api response in `Zendesk.handleList()and not return the whole response. So writing custom code was not an option.

2. Also, is there a timeline on fixing this issue for Zendesk API Client ?

**Comment by aheritier** [comment]
@srilavanyapaleti as you can see @zendesk closed the discussions on https://develop.zendesk.com/hc/en-us/articles/360022563994--BREAKING-New-Search-API-Result-Limits
You cannot search for more than 1000 items. At the Java API level I am not sure if we can improve the behavior. What does happen when we do a search with more than 1000 results ? The iterator fails ? Or it just returns the 100 entries properly ?

**Comment by srilavanyapaleti** [comment]
@aheritier  - The iterator fails to return the results if there are more than 1000 results. It is the problem with the Search API  which returns next_page as valid URL instead of returning null. Please refer to the below comments.
https://develop.zendesk.com/hc/en-us/articles/360001068607/comments/360004304393
https://develop.zendesk.com/hc/en-us/articles/360001068607/comments/360004307754

If we update the `handleList()` to stop at page 10, we could use the `count` parameter to split into batches of 1000 and repeat the search iteration. Do you think this could be an option to improve the Java API behavior?

**Comment by aheritier** [comment]
@srilavanyapaleti if we are limited at 1000 results how could we repeat the search ? This is what they are avoiding and I don't think there is a workaround?

I'm not against improving the java API to handle gracefully the limit of 10 pages / 1000 results (and the bad implementation proposed by zendesk which from my understanding still propose a 11 page on the next result .. :-/) but we have to take care if the code isn't shared with others iterators (like the ones for incremental exports) which do not have this limitation (but I know that the end of the iteration is detected differently)

**Comment by srilavanyapaleti** [comment]
@aheritier  - You are right. The solution I mentioned above will not work. It is going to use the same search url and limit the results. (I was wondering what is the point of having that count return all the results in Search API).

As mentioned by you, at this point it makes sense to update the iterator to stop at page 10 always.
