### ISSUE TITLE
Handling concurrent update for a ticket

### ISSUE THREAD

**Issue by andriiunitq** [cloudbees-oss/zendesk-java-client#376]
**Is your feature request related to a problem? Please describe.**
A ticket cannot be updated in parallel threads.
For example, I want to update tags for a ticket (I have several update requests) and the update requests will be executed at the same time, as a result, I'll lose the first update. 

The Zendesk official documentation provides the ability to handle it by specifying **safe_update + updated_stamp**, however, the zendesk-java-client doesn't allow to specify them.

https://developer.zendesk.com/rest_api/docs/support/tags

**Describe the solution you'd like**
According to documentation, we need to specify these params, so we can change the **PUT** tags endpoint and also update the Ticket or Request model.
`{
  "tags": ["customer"],
  "updated_stamp":"2019-09-12T21:45:16Z",
  "safe_update":"true"
}`
On the lower level **Status: 409 Conflict** error should be handled via creating a new type of exception.

**Comment by btpnlsl** [comment]
It's been over 12 years since this issue was opened, but I thought I would leave a comment here for anyone else who needs this functionality.

I found a way to work around this by creating a superclass of the `Ticket` class which has the `updated_stamp` and `safe_update` properties.   Here is an example in Kotlin, but you should be able to write similar code in Java.

```kotlin
class SafeUpdateTicket: Ticket() {
  @JsonProperty("safe_update")
  val safeUpdate: Boolean = true

  @JsonProperty("updated_stamp")
  fun getUpdatedStamp(): Date = updatedAt
}
```

Converting between a `Ticket` to a `SafeUpdateTicket` can be done with a Jackson ObjectMapper like so:

```kotlin
val ticket = zendeskClient.getTicket(ticketId)

// make changes to the ticket here

val safeUpdateTicket = objectMapper.convertValue<SafeUpdateTicket>(
    objectMapper.valueToTree(ticket)
)

val response = zendeskClient.updateTicket(safeUpdateTicket)
```
