### ISSUE TITLE
if you pass null, " " or "-1" to lookupUserByEmail(String email) method. it is returning all the users

### ISSUE THREAD

**Issue by benavid** [cloudbees-oss/zendesk-java-client#422]
**Describe the bug**
if you pass **null, " " or "-1"** to lookupUserByEmail(String email) method. it is returning all the users. I understand that this is not the expexted behaviour

I am creating the zendesk client as following:
`	  Zendesk zd = new Zendesk.Builder("<myurl>")
		        .setUsername("<myusername>")
		        .setToken("<mytoken>")
		        .build();`

and then call the method as following where userMail could be null, " ", "-1" or an existing email:
`Iterable<User> users = zd.lookupUserByEmail(userMail);
`
if you pass **null, " " or "-1"** the API return all the users

**To Reproduce**
Add a junit that call lookupUserByEmail(String email) with values **null, "" and "-1"**

**Expected behavior**
if the email **null**, **" "** or **"-1"** do not exist you should return empty iterable user

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
         No LSB modules are available.
         Distributor ID:	Ubuntu
         Description:	Ubuntu 20.04.3 LTS
         Release:	20.04
         Codename:	focal

 - Browser Google Chrome 96.0.4664.93
 - Version zendesk-java-client:0.15.0

**Additional context**

**Comment by aheritier** [comment]
hi @benavid 

Did you try the same with the official REST API?

On my side I get 

* https://foo.zendesk.com/api/v2/users/search.json?query=%22%22 => all users
* https://foo.zendesk.com/api/v2/users/search.json?query= ==> all users
* https://foo.zendesk.com/api/v2/users/search.json?query=-1 => 600 users
* https://foo.zendesk.com/api/v2/users/search.json?query=null => 4 users

When I refer to the docs

https://developer.zendesk.com/api-reference/ticketing/users/users/#search-users
https://developer.zendesk.com/api-reference/ticketing/ticket-management/search/

I am not sure what they are supposed to return for search searches but from my POV our code is flaky:

https://github.com/cloudbees-oss/zendesk-java-client/blob/master/src/main/java/org/zendesk/client/v2/Zendesk.java#L952

We do a search with `query=email` which I agree should return only the users with such email but if the email is used in a field which isn't the email it might be returned too

Not sure if we should do something like `query=email:foo%40acme.com` to have a better search but in that case we might miss users using `foo%40acme.com` as additional email ...

Not sure how to handle this better but I am afraid that the lib isn't doing worst than what the REST API does

cc @PierreBtz

**Comment by benavid** [comment]
Hi @aheritier, thanks for your response. ok I understannd that the official REST API has a similar behaviour and the client library only consume the official REST API, but perhaps the name of method in the client library **"lookupUserByEmail"** it is confusing for the library user. Because if I look for a user by email, the expectation is that there is no email with a null, -1 or empty value. Perhaps a query could be made on all the fields of the email type.
Currently we are assigning an email that we are sure does not exist when the value passed to us as a parameter is null, -1 or empty.

Regards,
Andres

**Comment by PierreBtz** [comment]
Unsure, maybe we could introduce a "strict mode" behind a flag, something like 

```
if (emailFieldOnly) {// strict mode
  // query=email:...
} else {
  // current behavior that looks up all fields
}
```

> Perhaps a query could be made on all the fields of the email type

In theory it looks like a good idea, but I'm unsure how we make such determination:
* how to make sure we evolve at the same time as ZD?
* what about custom fields? If a ZD is configured for instance with a field `secondaryEmail`, there is no way we can track it.

Other idea: we could introduce a brand new method where you would pass the fields you want to use in the lookup.

That being said, regarding your specific use case, is there something preventing you defining something like `private static final String NOT_AN_EMAIL="-1";` and then returning an empty collection if you detect your called with `NOT_AN_EMAIL`? Bonus, it would avoid a useless network call.

Or, if you are in a context where you know the pattern used for emails, you could use a regexp. This is something we cannot do at the library level since it's impossible to validate all possible email address format with a regexp.
