### ISSUE TITLE
PKIX path building failed: unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by hungbang** [cloudbees-oss/zendesk-java-client#439]
The app is using Spring boot and java 11. When we `createTicket`, we got the error below:
`Zendesk error java.net.ConnectException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
`

Zendesk java client version: 0.16.0

Please tell me how to resolve it. Thank you in advance

**Comment by aheritier** [comment]
Hi @hungbang 

You have a certificate issue at the JVM level. For some reason it doesn't find the root certificate used to validate the chain provided by zendesk.
It could be because you use a very old JVM, or you configured a custom certificates store and forgot to include the default ones or your store is corrupted.
You should look for Java TrustStore documentations and verify if you are using the default one and otherwise review/fix its content

Cheers

**Comment by hungbang** [comment]
@aheritier Thank you for responding. It's true that I have configured a custom cert to connect to amazon DocumentDB. Let me fix it. Thank you again.

**Comment by aheritier** [comment]
With pleasure @hungbang
