### ISSUE TITLE
Add Identity Type Enum or Constants

### ISSUE THREAD

**Issue by sebastienrougetenercoop** [cloudbees-oss/zendesk-java-client#453]
**Is your feature request related to a problem? Please describe.**
When building user Identity instances, I need to find available types easily, to avoid any mistake.

**Describe the solution you'd like**
Create an IdentityType enum, serializable as a well formatted string, with each allowed type.

**Describe alternatives you've considered**
Create constants in Identity class for each allowed type.

**Comment by aheritier** [comment]
@sebastienrougetenercoop I think it makes sense and it's not difficult to do.
The main issue is that it will beak (another time...) the API compatibility on the Java side

**Comment by aheritier** [comment]
@sebastienrougetenercoop I am not really annoyed about the API compatibility.
I should, for sure, but this project is in version 0.x.x for a decade and we had to broke several time the compatibility either because we did something wrong or because zendesk modified their APIs.
Replacing a String by an Enum won't be a big issue in a codebase. What is critical is to highlight it in our release notes
