### ISSUE TITLE
The total numbers doesn't match for articles

### ISSUE THREAD

**Issue by RobertoPegoraro** [cloudbees-oss/zendesk-java-client#574]
**Describe the bug**
When I perform the request zd.getArticles("ja") it returns 207 articles, but when I request using postman (Using the same credentials) in API https://myOrganization.zendesk.com/api/v2/help_center/ja/articles it returns 186 articles only.

**To Reproduce**
1. Request the articles from some locale in postman
2. Request the same articles for the same locale using the SDK

**Expected behavior**
Should be retrieved the exaclty number of articles

**Desktop (please complete the following information):**
 - OS: Mac OS Ventura 13.2.1
 - Postman Version 9.31.0
 - ZenDesk SDK Version 0.21.0
 - Java Version 11

**Comment by PierreBtz** [comment]
@RobertoPegoraro unsure why you observe such a different, it looks like the method you are using is calling exactly the same endpoint:

https://github.com/cloudbees-oss/zendesk-java-client/blob/master/src/main/java/org/zendesk/client/v2/Zendesk.java#L2237-L2240

Only thing I can think of is that in the case of postman you do not properly handle the pagination.

**Comment by RobertoPegoraro** [comment]
I found one reason, the API returns only the draft = false, while SDK returns all (draft = false and true). But even so, there is now 2 items of difference, API is returning 2 itens more than SDK

**Comment by PierreBtz** [comment]
I'm having a hard time figuring out what might go wrong since I cannot reproduce (our instance doesn't use help desk).
I'm also having a hard time figuring out why calling `/help_center/{locale}/articles.json` with curl gives a different answer since the calls are supposed to be identical.
My suggestion would be to activate the debug logs of the underlying http client (AsyncHttpClient by default) and check the exchanges between the library and the server.
